In [1]:
import pandas as pd

from pathlib import Path
from zipfile import ZipFile

In [2]:
# Special GeoNames pseudo-language / metadata tags.
# For name-generation / transduction, these are not ordinary language-name rows.
SPECIAL_ISOLANGUAGE = {
    "link",   # website link, mostly wikipedia
    "wkdt",   # wikidata id
    "post",   # postal code
    "iata",   # airport code
    "icao",   # airport code
    "faac",   # airport code
}

PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw" / "geonames"

GEONEAME_COLUMNS = [
        "geonameid",
        "name",
        "asciiname",
        "alternatenames",
        "latitude",
        "longitude",
        "feature_class",
        "feature_code",
        "country_code",
        "cc2",
        "admin1_code",
        "admin2_code",
        "admin3_code",
        "admin4_code",
        "population",
        "elevation",
        "dem",
        "timezone",
        "modification_date",
    ]

ALT_COLUMNS = [
        "alternate_name_id",
        "geonameid",
        "isolanguage",
        "alternate_name",
        "is_preferred_name",
        "is_short_name",
        "is_colloquial",
        "is_historic",
        "from_date",
        "to_date",
    ]

In [3]:
df_geonames = pd.read_csv(
        RAW_DIR / "allCountries.zip",
        sep="\t",
        header=None,
        names=GEONEAME_COLUMNS,
        nrows=5000,
        compression="infer",
        encoding="utf-8",
    )

In [4]:
df_geonames.head()

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature_class,feature_code,country_code,cc2,admin1_code,admin2_code,admin3_code,admin4_code,population,elevation,dem,timezone,modification_date
0,2994701,Roc Meler,Roc Meler,"Roc Mele,Roc Meler,Roc Mélé",42.58765,1.74180,T,PK,AD,"AD,FR",02,NaN,NaN,NaN,0,2811.0,2348,Europe/Andorra,2023-10-03
1,3017832,Pic de les Abelletes,Pic de les Abelletes,"Pic de la Font-Negre,Pic de la Font-Nègre,Pic ...",42.52535,1.73343,T,PK,AD,FR,A9,66,663.0,66146.0,0,NaN,2411,Europe/Andorra,2014-11-05
2,3017833,Estany de les Abelletes,Estany de les Abelletes,"Estany de les Abelletes,Etang de Font-Negre,Ét...",42.52915,1.73362,H,LK,AD,FR,A9,NaN,NaN,NaN,0,NaN,2260,Europe/Andorra,2014-11-05
3,3023203,Port Vieux de la Coume d’Ose,Port Vieux de la Coume d'Ose,"Port Vieux de Coume d'Ose,Port Vieux de Coume ...",42.62568,1.61823,T,PASS,AD,NaN,00,NaN,NaN,NaN,0,NaN,2687,Europe/Andorra,2014-11-05
4,3029315,Port de la Cabanette,Port de la Cabanette,"Port de la Cabanette,Porteille de la Cabanette",42.60000,1.73333,T,PASS,AD,"AD,FR",B3,09,91.0,9139.0,0,NaN,2379,Europe/Andorra,2014-11-05

In [5]:
with ZipFile(RAW_DIR / "alternateNamesV2.zip") as zf:
    with zf.open("alternateNamesV2.txt") as f:
        df_alternate_names = pd.read_csv(
            f,
            sep="\t",
            header=None,
            names=ALT_COLUMNS,
            dtype=str,
            keep_default_na=False,
            na_filter=False,
            nrows=10000,
        )

In [6]:
df_alternate_names.head()

,alternate_name_id,geonameid,isolanguage,alternate_name,is_preferred_name,is_short_name,is_colloquial,is_historic,from_date,to_date
0,1284819,2994701,,Roc Mélé,,,,,,
1,1284820,2994701,,Roc Meler,,,,,,
2,1291197,3017832,,Pic de les Abelletes,,,,,,
3,4290387,3017832,,Pic de la Font-Nègre,,,,,,
4,1291198,3017833,,Estany de les Abelletes,,,,,,

In [7]:
with ZipFile(RAW_DIR / "alternateNamesV2.zip") as zf:
        with zf.open("iso-languagecodes.txt") as f:
            df_lang = pd.read_csv(
                f,
                sep="\t",
                encoding="utf-8",
                dtype=str,
            )

In [8]:
df_lang.head()

  ISO 639-3 ISO 639-2 ISO 639-1           Language Name
0       NaN       afa       NaN  Afro-Asiatic languages
1       NaN       alg       NaN    Algonquian languages
2       NaN       apa       NaN        Apache languages
3       NaN       art       NaN    Artificial languages
4       NaN       ath       NaN    Athapascan languages