In [7]:
import pandas as pd
import sqlite3

pd.set_option('display.max_rows', None)

In [8]:
def run_query(query: str) -> pd.DataFrame:
    conn = sqlite3.connect("../data/geonames.sqlite")
    df = pd.read_sql_query(query, conn)
    return df

In [9]:
run_query("""
SELECT
    alternate_name,
    is_preferred_name,
    is_short_name,
    is_colloquial,
    is_historic,
    from_date,
    to_date,
    row_kind
FROM alternate_name
WHERE geonameid = 745044
ORDER BY
    is_preferred_name DESC,
    is_short_name DESC,
    is_historic ASC,
    alternate_name;
    """)

,alternate_name,is_preferred_name,is_short_name,is_colloquial,is_historic,from_date,to_date,row_kind
0,Estambul,1,0,0,0,None,None,name_lang
1,Istambul,1,0,0,0,None,None,name_lang
2,Istanbul,1,0,0,0,None,None,name_lang
3,Istanbul,1,0,0,0,None,None,name_lang
4,Istanbul,1,0,0,0,None,None,name_lang
5,Istanbul,1,0,0,0,None,None,name_lang
6,Istanbul,1,0,0,0,None,None,name_lang
7,Istanbul,1,0,0,0,None,None,name_lang
8,Istanbul,1,0,0,0,None,None,name_lang
9,Istanbul,1,0,0,0,None,None,name_lang
10,Istanbul,1,0,0,0,None,None,name_lang
11,Istanbul,1,0,0,0,None,None,name_untyped
12,Istanbul,1,0,0,0,None,None,name_lang
13,Istanbul,1,0,0,0,None,None,name_lang
14,Istanbul,1,0,0,0,None,None,name_lang
15,Istanbúl,1,0,0,0,None,None,name_lang
16,Isztambul,1,0,0,0,None,None,name_lang
17,Stambula,1,0,0,0,None,None,name_lang
18,Stambuł,1,0,0,0,None,None,name_lang
19,https://en.wikipedia.org/wiki/Istanbul,1,0,0,0,None,None,meta
20,İstanbul,1,0,0,0,None,None,name_lang
21,Ισταμπούλ,1,0,0,0,None,None,name_lang
22,Իսթանպուլ,1,0,0,0,None,None,name_lang
23,Ստամբուլ,1,0,0,0,None,None,name_lang
24,イスタンブール,1,0,0,0,None,None,name_lang
25,이스탄불,1,0,0,0,None,None,name_lang
26,34122,0,0,0,0,None,None,meta
27,Carigrad,0,0,0,0,None,None,name_lang
28,IST,0,0,0,0,None,None,meta
29,Istamboul,0,0,0,0,None,None,name_untyped
30,Istambul,0,0,0,0,None,None,name_untyped
31,Istambuł,0,0,0,0,None,None,name_lang
32,Q406,0,0,0,0,None,None,meta
33,TRIST,0,0,0,0,None,None,name_lang
34,http://id.loc.gov/authorities/names/n79034985,0,0,0,0,None,None,meta
35,https://no.wikipedia.org/wiki/Istanbul,0,0,0,0,None,None,meta
36,https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%...,0,0,0,0,None,None,meta
37,https://uk.wikipedia.org/wiki/%D0%A1%D1%82%D0%...,0,0,0,0,None,None,meta
38,Ισταμπουλ,0,0,0,0,None,None,name_lang
39,Истанбул,0,0,0,0,None,None,name_lang
40,Истанбул,0,0,0,0,None,None,name_lang
41,Стамбол,0,0,0,0,None,None,name_lang
42,Стамбул,0,0,0,0,None,None,name_lang
43,Стамбул,0,0,0,0,None,None,name_lang
44,ביזנטיון,0,0,0,0,None,None,name_lang
45,اسطنبول,0,0,0,0,None,None,name_lang
46,इस्तांबुल,0,0,0,0,None,None,name_lang
47,ইস্তাম্বুল,0,0,0,0,None,None,name_lang
48,ビュザンティオン,0,0,0,0,None,None,name_lang
49,伊斯坦堡,0,0,0,0,None,None,name_lang
50,伊斯坦堡,0,0,0,0,None,None,name_lang
51,伊斯坦布尔,0,0,0,0,None,None,name_lang
52,비잔티움,0,0,0,0,None,None,name_lang
53,Bizánc,0,0,0,1,None,None,name_lang
54,Byzance,0,0,0,1,None,None,name_lang
55,Byzantion,0,0,0,1,None,None,name_untyped
56,Byzantion,0,0,0,1,None,None,name_lang
57,Byzantion,0,0,0,1,None,None,name_lang
58,Byzantion,0,0,0,1,None,None,name_lang
59,Byzantion,0,0,0,1,None,None,name_lang
60,Byzantion,0,0,0,1,None,None,name_lang
61,Byzantium,0,0,0,1,None,None,name_lang
62,Byzantium,0,0,0,1,None,None,name_lang
63,Byzanz,0,0,0,1,None,None,name_lang
64,Carigrad,0,0,0,1,None,None,name_lang
65,Constantinoble,0,0,0,1,None,None,name_lang
66,Constantinopla,0,0,0,1,None,None,name_lang
67,Constantinople,0,0,0,1,None,None,name_lang
68,Constantinopolen,0,0,0,1,None,None,name_lang
69,Constantinopoli,0,0,0,1,None,None,name_untyped
70,Constantinopolis,0,0,0,1,None,None,name_untyped
71,Costantinopoli,0,0,0,1,None,None,name_lang
72,Konstantinopel,0,0,0,1,None,None,name_untyped
73,Konstantinopel,0,0,0,1,None,None,name_lang
74,Konstantinopel,0,0,0,1,None,None,name_lang
75,Konstantinopol,0,0,0,1,None,None,name_lang
76,Konstantinopolo,0,0,0,1,None,None,name_lang
77,Konstantinoupolis,0,0,0,1,None,None,name_untyped
78,Konstantinápoly,0,0,0,1,None,None,name_lang
79,Kustantiniyah,0,0,0,1,None,None,name_untyped
80,Micklagård,0,0,0,1,None,None,name_lang
81,Mikligarður,0,0,0,1,None,None,name_lang
82,Stamboul,0,0,0,1,None,None,name_untyped
83,Stambul,0,0,0,1,None,None,name_untyped
84,Tsarigrad,0,0,0,1,None,None,name_lang
85,https://en.wikipedia.org/wiki/Constantinople,0,0,0,1,None,None,meta
86,Βυζάντιο,0,0,0,1,None,None,name_lang
87,Βυζαντιο,0,0,0,1,None,None,name_lang
88,Κωνσταντινουπολη,0,0,0,1,None,None,name_lang
89,Κωνσταντινούπολη,0,0,0,1,None,None,name_lang
90,Κωνσταντινούπολις,0,0,0,1,None,None,name_untyped
91,στην Πόλι [stimˈboli],0,0,0,1,None,None,name_lang
92,Византија (Vizantija),0,0,0,1,None,None,name_lang
93,Բյուզանդիոն,0,0,0,1,None,None,name_lang
94,Կոստանդնուպոլիս,0,0,0,1,None,None,name_lang
95,Կոստանդնուպոլիս,0,0,0,1,None,None,name_lang

In [10]:
run_query("""
SELECT
    isolanguage,
    alternate_name,
    is_preferred_name,
    is_historic,
    from_date,
    to_date
FROM alternate_name
WHERE geonameid = 745044
  AND (
      isolanguage = 'la'
      OR lower(alternate_name) LIKE 'constantin%'
      OR lower(alternate_name) LIKE 'nova roma%'
      OR lower(alternate_name) LIKE 'byzant%'
  )
ORDER BY isolanguage, alternate_name;
""")

,isolanguage,alternate_name,is_preferred_name,is_historic,from_date,to_date
0,,Byzantion,0,1,None,None
1,,Constantinopoli,0,1,None,None
2,,Constantinopolis,0,1,None,None
3,ca,Constantinoble,0,1,None,None
4,cs,Byzantion,0,1,None,None
5,de,Byzantion,0,1,None,None
6,en,Byzantium,0,1,None,None
7,en,Constantinople,0,1,None,None
8,es,Constantinopla,0,1,None,None
9,fi,Byzantion,0,1,None,None
10,la,Byzantium,0,1,None,None
11,nl,Constantinopolen,0,1,None,None
12,sk,Byzantion,0,1,None,None
13,sv,Byzantion,0,1,None,None